haproxy_package: haproxy
haproxy_service_name: haproxy
haproxy_conf_dir: "/etc/haproxy/conf.d"
haproxy_cfg: "/etc/haproxy/haproxy.cfg"
haproxy_tcp_vhosts: []
haproxy_http_vhosts: []

acme_email: "victorrouviere3@gmail.com"
cloudflare_api_token: "xxxxxxxxxxxxxxxxxxxx"
