haproxy_tcp_vhosts:
  
  - name: www.devver.app
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i www.devver.app }"
    backend:
      ip: 192.168.45.50
      port: 443

  - name: devver.app
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i devver.app }"
    backend:
      ip: 192.168.45.50
      port: 443
  
  - name: app.devver.app
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i app.devver.app }"
    backend:
      ip: 192.168.45.50
      port: 443

  - name: docs.devver.app
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i docs.devver.app }"
    backend:
      ip: 192.168.45.50
      port: 443

  - name: logto.devver.app
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i logto.devver.app }"
    backend:
      ip: 192.168.45.50
      port: 443

  - name: auth.devver.app
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i auth.devver.app }"
    backend:
      ip: 192.168.45.50
      port: 443

  - name: devver
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i devver.vrhometech.fr }"
    backend:
      ip: 192.168.45.99
      port: 443

  - name: nextcloud.vrhometech.fr
    frontend: 443
    type: tcp
    accept_rule: "{ req_ssl_sni -i nextcloud.vrhometech.fr }"
    backend:
      ip: 192.168.20.6
      port: 443
 
  


